In [5]:
# This is a code cell.
# To execute cells, press Shift + Enter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

This is a markdown cell.<br>
My name is <b>Sid</b>.

In [6]:
2 + 3

5

In [7]:
print("Hello World!")

Hello World!


In [9]:
np.random.rand(5)

array([0.18005488, 0.11541471, 0.00144803, 0.76971421, 0.38847719])

In [8]:
np.random.rand(5, 5)

array([[0.68154976, 0.42676234, 0.5626467 , 0.84297965, 0.24779756],
       [0.55558503, 0.21368382, 0.99431986, 0.0396757 , 0.87225869],
       [0.41847869, 0.57908118, 0.42781849, 0.105868  , 0.17799921],
       [0.41591215, 0.34527882, 0.3097492 , 0.92569227, 0.31275015],
       [0.27447294, 0.9795225 , 0.36735867, 0.22124702, 0.94327281]])

In [10]:
np.random.randint(1, 10, 5)

array([4, 2, 1, 3, 2], dtype=int32)

In [14]:
np.array([1, 2, 3]) * 2

array([2, 4, 6])

In [13]:
[2, 3, 5, "Hello"] * 2

[2, 3, 5, 'Hello', 2, 3, 5, 'Hello']

In [16]:
np.array([2, 3, 5, 7]) * 2

array([ 4,  6, 10, 14])

In [17]:
values = np.array([2, 3, 5, 7])
for value in values:
    print(value * 2)

4
6
10
14


In [20]:
values * 2   # Broadcasting example

array([ 4,  6, 10, 14])

In [22]:
# List Comprehension
output = [value * 2 for value in values]
print(output)

[np.int64(4), np.int64(6), np.int64(10), np.int64(14)]


In [23]:
np.array(
    [2.3, 4.5, 6.7, 8.9]
)

array([2.3, 4.5, 6.7, 8.9])

In [25]:
np.array(
    [[2.3, 4.5, 6.7, 8.9],
    [3.3, 5.5, 7.7, 9.9],
    [4.4, 6.6, 8.8, 10.1]]
)

array([[ 2.3,  4.5,  6.7,  8.9],
       [ 3.3,  5.5,  7.7,  9.9],
       [ 4.4,  6.6,  8.8, 10.1]])

In [34]:
# Indexing and Slicing
x1 = np.array(
    [2.3, 4.5, 6.7, 8.9]
)

In [35]:
x1[0]

np.float64(2.3)

In [36]:
x1[-1]

np.float64(8.9)

In [37]:
x1[-2]

np.float64(6.7)

In [38]:
x1[0:2]  # 2 is exclusive

array([2.3, 4.5])

In [47]:
x2 = np.array(
    [[2.3, 4.5, 6.7, 8.9],
    [3.3, 15.5, 7.7, 9.9],
    [4.4, 6.6, 8.8, 10.1]]
)

In [48]:
x2[1][2]

np.float64(7.7)

In [49]:
# Basic Stats
x1.min()

np.float64(2.3)

In [50]:
x1.max()

np.float64(8.9)

In [51]:
x1.mean()

np.float64(5.6)

In [52]:
x1.std()

np.float64(2.459674775249769)

In [53]:
x1.sum()

np.float64(22.4)

In [54]:
x2.min()

np.float64(2.3)

In [55]:
x2.max()

np.float64(15.5)

In [56]:
x2.max(axis = 0)

array([ 4.4, 15.5,  8.8, 10.1])

In [57]:
x2.max(axis = 1)

array([ 8.9, 15.5, 10.1])

In [58]:
x2.mean(axis = 1)

array([5.6  , 9.1  , 7.475])

In [59]:
np.sqrt(x2)

array([[1.51657509, 2.12132034, 2.58843582, 2.98328678],
       [1.81659021, 3.93700394, 2.77488739, 3.14642654],
       [2.0976177 , 2.56904652, 2.96647939, 3.17804972]])

In [60]:
np.log(x2.mean(axis = 1))

array([1.7227666 , 2.20827441, 2.01156412])

In [ ]:
def calculate_squareroot(x: float) -> float:
    """Calculate the square root of a number."""
    return np.sqrt(x)

In [62]:
original_value = 16.0
square_root = calculate_squareroot(original_value)
print(f"The square root of {original_value} is {square_root}")

The square root of 16.0 is 4.0


In [63]:
original_value = 239.45
square_root = calculate_squareroot(original_value)
print(f"The square root of {original_value} is {square_root}")

The square root of 239.45 is 15.474172029546525


In [ ]:
original_value = 239
square_root = calculate_squareroot(original_value)
print(f"The square root of {original_value} is {square_root}")

The square root of 239 is 15.459624833740307
